spring.datasource.url=jdbc:postgresql://ep-delicate-glitter-am0ijqn1-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KzEnxpNJj1Q2

server.port=8080
