spring.application.name=calibrationapp

spring.datasource.url=jdbc:postgresql://ep-delicate-glitter-am0ijqn1-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KzEnxpNJj1Q2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.address=0.0.0.0
server.servlet.context-path=/calibapp

server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true

spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}